apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-persistent-storage-claim
spec:
  resources:
    requests:
      storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
